sudo: required
os: linux
dist: xenial
language: node_js
node_js:
- lts/*
env:
  global:
  - BUILD_VERSION=0.04
  - CCACHE_SIZE=100M
  - CCACHE_TEMPDIR=/tmp/.ccache-temp
  - CCACHE_COMPRESS=1
cache:
  apt: true
  directories:
  - "$HOME/google-cloud-sdk/"
  - "$HOME/.ccache"
matrix:
  fast_finish: true
  include:
  - env: BUILD_ICONS=assets/icons/agama_icons/128x128.png IGNORE_OS_ASSETS_1=assets/bin/osx
      IGNORE_OS_ASSETS_2=assets/bin/win64 TARGET_PLATFORM=linux BUILD_DIR=Agama-linux-x64
      ASSETS_DIR=linux64 BUILD_VARIANT=Linux64
  - env: BUILD_ICONS=assets/icons/agama_icons/agama_app_icon.ico IGNORE_OS_ASSETS_1=assets/bin/osx
      IGNORE_OS_ASSETS_2=assets/bin/linux64 TARGET_PLATFORM=win32 BUILD_DIR=Agama-win32-x64
      PACKAGES=winehq-devel ASSETS_DIR=win64 BUILD_VARIANT=Win64
before_install:
- openssl aes-256-cbc -K $encrypted_a41fbd06a4b9_key -iv $encrypted_a41fbd06a4b9_iv
  -in AUTH_KEY.json.enc -out AUTH_KEY.json -d
- npm install electron-packager -g && npm install electron -g --unsafe-perm=true && npm install
- gcloud auth activate-service-account --key-file AUTH_KEY.json
- rm AUTH_KEY.json && rm AUTH_KEY.json.enc
- mkdir -p assets/bin/$ASSETS_DIR
- gsutil cp gs://$BUCKET/$ARTIFACTS/$TRAVIS_BRANCH/$BUILD_VARIANT.tar.gz . || gs://$BUCKET/$ARTIFACTS/master/$BUILD_VARIANT.tar.gz .
- tar -xzvf $BUILD_VARIANT.tar.gz && rm $BUILD_VARIANT.tar.gz
- cp -rvf $BUILD_VARIANT/* assets/bin/$ASSETS_DIR
- cd gui/EasyDEX-GUI/react && gsutil cp gs://$BUCKET/EasyDEX-GUI/$TRAVIS_BRANCH/build.tar.gz .
- tar -xzvf build.tar.gz && rm build.tar.gz
- cd ../../..
install:
- if [ -n "$PACKAGES" ]; then sudo rm -f /etc/apt/sources.list.d/travis_ci_zeromq3-source.list;
  fi
- if [ -n "$PACKAGES" ]; then sudo dpkg --add-architecture i386 && wget -nc https://dl.winehq.org/wine-builds/Release.key;
  fi
- if [ -n "$PACKAGES" ]; then sudo apt-key add Release.key; fi
- if [ -n "$PACKAGES" ]; then sudo apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/;
  fi
- if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get update && sudo apt-get -y
  install --install-recommends -qq $PACKAGES; fi
- npm install
script:
- electron-packager . --platform=$TARGET_PLATFORM --arch=x64 --icon=$BUILD_ICONS --out=build/
  --buildVersion=$BUILD_VERSION --ignore=$IGNORE_OS_ASSETS_1 --ignore=$IGNORE_OS_ASSETS_2
  --overwrite
after_script:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then cd build && tar -czf $BUILD_DIR.tar.gz $BUILD_DIR && gsutil cp $BUILD_DIR.tar.gz gs://$BUCKET/$PROJECT/$TRAVIS_BRANCH/;
  fi
notifications:
  slack:
    secure: EtJmqOQWaSaZaKL8JthAD9xD2ztooM9l5bbtFFYo4DaDI17LcNrsAi6DHJP9qo3VcbKYUgTpQ1X8bIOmV8V3JXPXvKZB8PVRcziDdCYVTlXdaILleQMfLeOEujI5MzwqmOt9RgRLLn436w4UgeXoSdox4lszceCXbZHLNPxspFYpW8BPi/ZQIppyQ3Nk/2B8KXqjzeSzrKs3Ydj24uwoPRlOcdCv77dXAzFU00tX2/vy/23qV0+Ak9b3d7+UbOq8Y7rsrYkQDeyYthV1Kka+IsKW+ed9+bZW/grgvKGf3+eHK5dmIgI3SCVioVcC1EMVLi/84x/my7lTSzcqQOotPNeMLVcuRO0pR6cQq6wQpnHtuoAZ//zG/tQSvdz1XU4HYxU5ahHyK0idHbN23MZaQsT/6TzQ+4oVaoWwDgU52b2KHCJkxMl/6yNU+YUuMf9ypKZTy5YiQfhtYK5Lus0pLyXAVrwkmP/9itgv6ubeM8XwVJ/RvsZt/zxCyQ7J0yO8E3lV/KCbAGdNipek3m+0HRQOFk7Gl3V1DNDUqfVXz151O1Suf4m6aqBX6hFTJ80SRgc7Cc3+JdfueDuhxLBu6c2GBipYWqlaxPml/pvhMMbH0TxtfBY6CtGk+61GfInFAPz2TyCBkgos2uAnUKo5tB2kqgwf2WWC546q3BkqZ5Q=
